### PR TITLE
Use gcammisa's port to fix issues

### PR DESCRIPTION
**Pull request by Steinhagen**
Modifying the source to gcamisa's port, we are fixing the following issues:
1. Greatly improved sharpness, particularly in fullscreen mode
2. Multimonitor support
3. Working Japanese support
4. Audio muting doesn't summon demons

More details about this can be found in issue #12.

### CODE REVIEW

**Comment by FakeShemp** [comment]
Since this is a completely new port with different developers it should probably be in a new manifest, like `com.github.gcammisa.KatawaShoujo-RenPy8`.

**Comment by Steinhagen** [comment]
I'm not to sure about this. This will only create more confusion between the original Katawa Shoujo application and this one for normal users.

**Comment by FakeShemp** [comment]
@barthalion @hfiguiere
What's your opinions?

**Comment by barthalion** [comment]
The fact it ditches a lot of dependencies make it sound like it's a binary build. It should be built from source instead to keep compatibility with aarch64.

**Comment by Steinhagen** [comment]
So if we rebuilding this ourselves (instead of taking their built binaries), will be good enough to merge this under this manifest name?

**Comment by barthalion** [comment]
Sure.

**Comment by Steinhagen** [comment]
I changed the manifest to compile the game and use renpy rather than use their binaries. From what I can tell, everything works as expected.

From the limited testing I did, the only warning/issue that I can find is that renpy is by default is trying to write/binary a number of files and that's not compatible with the way flatpak mounts the /app directory (read-only). These files can eventually be moved to var/data and be symlink in app, but I'm not sure if that's the correct way of doing things for renpy.

Other than this, I haven't found any issue with the port and pretty much everything looked to work (save/load, sound, localization, videos, etc.)

**Comment by FakeShemp** [comment]
Works for me as well. Great work!

**Pull request merged**
